# 추후 서버 환경에서 사용하는 정보들 application-server.yml 파일에 설정

Spring:
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  datasource:
    url: jdbc:mysql://[aws rds endpoint]/test?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
    username: [rds admin id]
    password: [rds admin pw]
    driver-class-name: com.mysql.cj.jdbc.Driver
config:
  domain: [aws s3 Endpoint]
