Spring:
  jpa:
    hibernate:
      ddl-auto: create-drop  # (1) 스키마 자동 생성

    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  datasource:
    url: jdbc:mysql://questiondb.cyzxb0mcvfbt.ap-northeast-2.rds.amazonaws.com:13306/test?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
    username: admin
    password: nYnGPet4XOBeZ2wkFLfU
    driver-class-name: com.mysql.cj.jdbc.Driver

config:
  domain: http://pre-19.s3-website.ap-northeast-2.amazonaws.com:8080

#JWT 관련 spec
mail:
  address:
    admin: test@gmail.com

jwt:
  secret-key: 1q2w3e4r5t6y7u8i9o0p!@#$%^&*()1q2w3e4r5t6y7u8i9o0p
  access-token-expiration-minutes: 120
  refresh-token-expiration-minutes: 500