# 로컬 환경에서 사용하는 정보들 application-local.yml 파일에 설정
spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:test
  jpa:
    hibernate:
      ddl-auto: create-drop  # (1) 스키마 자동 생성
    show-sql: true      # (2) SQL 쿼리 출력
    properties:
      hibernate:
        format_sql: true  # (3) SQL pretty print
  sql:
    init:
      data-locations: classpath*:db/h2/data.sql
logging:
  level:
    org:
      springframework:
        orm:
          jpa: DEBUG
#postman 한글깨짐 현상을 없애기 위해 추가함.
server:
  servlet:
    encoding:
      force-response: true
      charset: utf-8
      force: true


#JWT 관련 spec
mail:
  address:
    admin: test@gmail.com

jwt:
  secret-key: ${JWT_SECRET_KEY} #256bit 이상안하면 tokenizer에서 거절함.
  access-token-expiration-minutes: 1
  refresh-token-expiration-minutes: 420